CREATE DATABASE IF NOT EXISTS job_notes DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE job_notes;

DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO user (username, password) VALUES ('user1', '123456'), ('user2', '123456');

CREATE TABLE user_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL UNIQUE,
    education VARCHAR(20) DEFAULT NULL COMMENT '学历：大专/本科/硕士/博士',
    skill_list TEXT DEFAULT NULL COMMENT '求职者技能列表，逗号分隔',
    expected_salary VARCHAR(50) DEFAULT NULL COMMENT '期望薪资',
    expected_city VARCHAR(50) DEFAULT NULL COMMENT '期望城市',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE job (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    company_name VARCHAR(100) NOT NULL,
    position_name VARCHAR(100) NOT NULL,
    job_link VARCHAR(500) DEFAULT NULL,
    salary_range VARCHAR(50) DEFAULT NULL COMMENT '薪资范围',
    region VARCHAR(50) DEFAULT NULL COMMENT '地区',
    apply_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL COMMENT 'APPLIED/INTERVIEWING/OFFERED/REJECTED/ABANDONED',
    remark TEXT DEFAULT NULL,
    min_education VARCHAR(20) DEFAULT NULL COMMENT '岗位要求最低学历',
    required_skill TEXT DEFAULT NULL COMMENT '岗位要求的技能',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE note (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    note_type VARCHAR(20) NOT NULL COMMENT 'SKILL/INSIGHT',
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_job FOREIGN KEY (job_id) REFERENCES job(id) ON DELETE CASCADE,
    CONSTRAINT fk_note_user FOREIGN KEY (user_id) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
